### PR TITLE
fix: date logic

### LINKED ISSUE #127: post page: render date correctly

### PR DESCRIPTION
**Pull request by riraum**
fix #127

https://github.com/mattn/go-sqlite3/issues/142#issuecomment-65295974
https://pkg.go.dev/github.com/mxk/go-sqlite/sqlite3

### CODE REVIEW

File: http/http.go [hunk 1]
```diff
@@ -91,14 +92,24 @@ func parseRValues(r *http.Request) (db.Post, error) {
...
+	// 	return p, fmt.Errorf("date convert to float: %w", err)
+	// }
+	time, err := time.Parse(time.DateOnly, date)
+	if err != nil {
+		return p, fmt.Errorf("date parse: %w", err)
 	}
+	log.Println("print time parse:", time)
+
+	p.Date = time.Unix()
+	// }
```
Comment (riraum) [inline http/http.go:112]: currently gets me `failed to parse values: date parse: parsing time "" as "2006-01-02": cannot parse "" as "2006"
exit status 1` during a test via the frontend.
